### ISSUE TITLE
Per Arena different number of players

### ISSUE THREAD

**Issue by GiuseppeGroth** [caseif/TTT#18]
Hello,

you could install that each arena has a number of own players, Min and Max Player.
so that one can say if it'

Hallo,

ich habe verschiedene Arenen könntest du einbauen dass es mit den Min und Max Spielern Varieren kann pro Arena

So kann man Kleineren Arenen weniger Spieler zu weisen

ein Vote System wäre auch cool wenn man eine Runder verfrüht beginnen will.
bzw. auch eine andere Map will

**Comment by caseif** [comment]
Accepted.

**Comment by Crypnotic** [comment]
Implementing per arena minimum/maximum players counts shouldn't be too difficult. However, I do think it would be wise to keep the current approach as a config option as it might fit some server setups better. Possibly a <code>player-count=fixed/dynamic</code>

<code>Fixed: Config based min/max. "Legacy"</code>

<code>Dynamic: Maximum player count determined on arena spawn points or operator defined. Minimum player count determined by a percentage of arena spawns taken or operator defined</code>

**Comment by caseif** [comment]
@Crypnotic I like that idea, although I might allow limits to be configured regardless of the standard behavior.

**Comment by caseif** [comment]
Added via 18ea2ca1a007fe184a45201c85d9fa02b62a4774 and 9eb260f39a8e53dc7e2230da8b9dd611f9710e31.
