### ISSUE TITLE
invisible player

### ISSUE THREAD

**Issue by mathis-kdio** [caseif/TTT#19]
As soon as one deviates players during a game , they disappear and you do not see them.

**Comment by caseif** [comment]
Could you explain the steps that lead to this bug? It'll help me track down what exactly is causing it.

**Comment by TheMeq** [comment]
When a player is killed, all the players on the map go invisible. I'm not sure what causes it.

**Comment by TheMeq** [comment]
Actually, it doesn't matter if they are killed or not, they just turn invisible randomly

**Comment by TheMeq** [comment]
but it's everyone at the same time, not just individual players.

**Comment by caseif** [comment]
That may be because of some trickery MGLib does to keep players not in the round off of the tab list. I'll look into it and try to fix it for the next release.

**Comment by TheMeq** [comment]
aside from the invisibility gltcih, everything else works perfectly!

**Comment by mathis-kdio** [comment]
Yes, that's exactly it .

**Comment by mathis-kdio** [comment]
Did you find the problem?

**Comment by caseif** [comment]
@mattuys Yes, it should be fixed in the next release.

**Comment by mathis-kdio** [comment]
Ok cool

**Comment by TheMeq** [comment]
Sweet! Can't wait for the update!
