### ISSUE TITLE
Water not flowing

### ISSUE THREAD

**Issue by SteamingSugar** [caseif/TTT#23]
Water is not flowing in worlds that are setup with TTT, I have tested this by disabling TTT and the water can flow.

**Comment by caseif** [comment]
Works as intended. MGLib's rollback engine is not intuitive enough to roll back events such as this, so they are disabled within arenas. You can re-enable them in the `config.yml`, but know that they will most likely not be rolled back.

**Comment by SteamingSugar** [comment]
Where in config? can't find it

**Comment by caseif** [comment]
[Here.](https://github.com/caseif/TTT/blob/master/src/main/resources/config.yml#L145)

**Edit:** Actually, that should be permitted by default. It might be called as a block spread event instead, so you may need to play around with the config a bit.

**Comment by caseif** [comment]
Reopening, as this will be fixed in 0.8.0.
