### ISSUE TITLE
DNA Decay

### ISSUE THREAD

**Issue by caseif** [caseif/TTT#25]
DNA on bodies should "decay" after a certain (configurable) time period.

**Comment by caseif** [comment]
Added via [`65a657e`](https://github.com/caseif/TTT/commit/65a657e54664f39441e373cf5729dfb2913c81a1).

**Comment by ghost** [comment]
So you The Chest Disappears? For After Certain Amount Of Time? 
Nice =D

**Comment by caseif** [comment]
@Junhaochia The chest remains until the round ends, but after a certain time it will not be possible for detectives to collect DNA from it anymore.
