### ISSUE TITLE
Joining arenas after creation not working

### ISSUE THREAD

**Issue by Aviriix** [caseif/TTT#28]
Hello,

I created an arena using your latest version of TTT (V0.8.2), and created an arena. After I did this it said the arena was successfully created and could be joined with /TTT join <arena>. I tried to do this, but when I tried this it said that the arena didnt exist. I checked using the listarenas command, and the arena was on the list, marked as 'WAITING'. I tried adding another spawn, which gave me the same message as when I tried to join the arena. I'm running the latest spigot version, and am using Java 8.

**Comment by caseif** [comment]
What was the ID of the arena?

**Comment by Aviriix** [comment]
The arena id is: ashborne

**Comment by caseif** [comment]
Can you upload a paste of your `plugins/TTT/flint_data/arenas.yml` file?

Edit: Also, did you create the arena via the wizard, or via the `import` command?

**Comment by Aviriix** [comment]
I created the arena using the wizard, here is the paste:

§cashborne:
  name: §cashborne
  world: world
  spawns:
    '0': ("world";964,5901611392226;73,0;-580,3000000119209)
  bound:
    upper: (1029,0;256,0;-538,0)
    lower: (899,0;0,0;-627,0)
  metadata: {}

**Comment by caseif** [comment]
I'm assuming the `§c` wasn't your doing?

**Comment by Aviriix** [comment]
Yes, I didnt add those myself

**Comment by caseif** [comment]
Okay. That's, ah, really strange. I'll take a look at it as soon as I can. Stay in touch in case I need more information later on. :)

**Comment by Aviriix** [comment]
Alright, thanks a lot for the support :)

**Comment by caseif** [comment]
Actually, do you perchance have a chat plugin installed that changes message colors? Would you mind pasting the output of `/pl`?

**Comment by Aviriix** [comment]
I do, I use the plugin RankPrefix+. I also had to unload that plugin for the 'OK' at the end of the wizard to get noticed

**Comment by caseif** [comment]
Mm, that would do it. I'll try to get a hotfix out tomorrow or Tuesday to fix this.

**Comment by Aviriix** [comment]
Alright, thanks a lot! :)

**Comment by caseif** [comment]
My pleasure. :)

**Comment by caseif** [comment]
Closed via [`3007244`](https://github.com/caseif/TTT/commit/3007244).
