### ISSUE TITLE
Dead bodies don't dissapear

### ISSUE THREAD

**Issue by agronaque512** [caseif/TTT#36]
All in the title.
Dead "chest" bodies don't ever dissapear. Players coming back in game and see all that "chest" bodies from the last game.
I use the latest build 0.9.2
And i got this error from steel i use Spigot 1.8.8R0.1
How2Fix ?

**Comment by Junhaochia** [comment]
Steel?

**Comment by ghost** [comment]
Do you have the lastest version of Steel?

**Comment by agronaque512** [comment]
Yes V1.1.3 (plugman say it)

**Comment by ghost** [comment]
Well they disappears for me what java version , your server is running on? Recommended 8*

**Comment by agronaque512** [comment]
Java 8.

**Comment by Junhaochia** [comment]
Private server? Maybe I can hop on see what's da problem

**Comment by agronaque512** [comment]
You want the IP of the server ?

**Comment by ghost** [comment]
Nah, btw my test server version snapshot name : git-spigot-6c9b0a1-De5c261 (1.8.8 R0.1 snapshot)

**Comment by agronaque512** [comment]
I just want a solution... Any idea?

**Comment by ghost** [comment]
Try removing the chest  and play again well it's was fix 1 version back

**Comment by agronaque512** [comment]
I will probably create a new issue when i got the time to test it again then. For now i will just disable it.... Cause CHEST EVERYWHERE :D

**Comment by caseif** [comment]
It's very possible that I somehow borked the rollback database again. I'll look further into the issue when I get home later tonight.

**Comment by caseif** [comment]
@agronaque512 Could you make a copy of the `plugins/TTT/flint_data/rollback.db` file during the round end period (after bodies have been created, but before they're meant to be rolled back) and attach it in a comment?

**Comment by Junhaochia** [comment]
+caseif how to make it that items show in the chest?

**Comment by caseif** [comment]
@Junhaochia What do you mean?

**Comment by Junhaochia** [comment]
@caseif like the data for the chest. The DNA thingy.

**Comment by caseif** [comment]
What do you want to do with it?

**Comment by Junhaochia** [comment]
Btw how high is your level of coding for plugin?

**Comment by caseif** [comment]
@Junhaochia I'm not quite sure I understand what you're asking.

**Comment by agronaque512** [comment]
@caseif Sorry bro it made me mad so i deleted it. lel.

**Comment by caseif** [comment]
@agronaque512 If this is a legitimate issue with the plugin as it seems to be, I'd like to be able to get to the bottom of it. If you send me a copy your rollback database (`plugins/TTT/flint_data/rollback.db`) after players have died but before the round ends, I may be able to patch it and get it fully working again or at least make a start on finding the issue.
