### ISSUE TITLE
Rewrite config validator

### ISSUE THREAD

**Issue by caseif** [caseif/TTT#38]
Currently, the config validator operates on a line-by-line basis so as to preserve comments and the like. However, this does not support nested keys or lists and bars the TTT config from using them. The validator needs to be rewritten or otherwise modified to account for this.

**Comment by MCG-server** [comment]
What do you mean by that ??
that there is in the version 0.10 of the traitor-tester ??

**Comment by caseif** [comment]
@MCG-server The config validator is an internal system and has nothing to do with traitor testers.

**Comment by MCG-server** [comment]
and how do I do this?
