### ISSUE TITLE
shop

### ISSUE THREAD

**Issue by MCG-server** [caseif/TTT#45]
After this I do not break you more (for bugs), how do I open the shop of the traitor and the detective ?? another thing where do I fit in your plugin ?? if you put if I want to improve one thing is you want to show the (eclipse use) (if you send me to fuck off, cpisco)

**Comment by MCG-server** [comment]
(If you send me to fuck off, I understand)

**Comment by caseif** [comment]
Shops are also a planned feature. Please review existing issues before creating a new one.
