### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by HotelMakar** [caseif/TTT#47]
## TTT Version

0.10.0
## Steel Version

1.2.1
## Full output of `/version` command

This server is running CraftBukkit version git-Bukkit-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT) Checking version, please wait... You are 358 version(s) behind
## Description of issue

When I type OK nothing happens and arena did not create
## Steps to replicate issue

Step 1 /ttt carena
Step 2 i wrote the name as TEST
Step 3 i right click and left click the side of the arena
Step 4 i type OK to set spawnpoint then nothing happens
## Does the issue occur consistently?

(That is, can you replicate the issue every time you take the steps described above?)

Yes
## Console Errors?

If you're receiving console errors from TTT, please upload them to [Pastebin](https://pastebin.com/) and enter the link here.
http://pastebin.com/npGzhuGA

**Comment by caseif** [comment]
Hm, this seems to be a common issue but I'm not entirely sure why. In any case, assuming you've already tried restarting the server, recompiling Craftbukkit via BuildTools should do the trick. I think I'm going to start including Gson with the TTT binary, though, to avoid problems like this in the future.

If you don't want to recompile, keep an eye out for a 0.10.1 version in the next day or two.

**Comment by caseif** [comment]
Never mind, I've identified the problem, which lies in Steel. I'll try to get a version 1.2.2 out tonight.

**Comment by HotelMakar** [comment]
reply me once it's out thanks

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by caseif** [comment]
Resolved via [Steel v1.2.2](https://github.com/caseif/Steel/releases/tag/v1.2.2).
