### ISSUE TITLE
Economy support

### ISSUE THREAD

**Issue by ghost** [caseif/TTT#54]
Hi
I posted a review saying that economy support would be awesome.
With that, I meant: it would be cool if you add support for Vault, that when you win the game, you get a reward :)
(Sorry for my bad English, I'm Italian :)

**Comment by caseif** [comment]
Would being able to define commands on victory/defeat suffice?

**Comment by ghost** [comment]
What do you mean by that?

**Comment by caseif** [comment]
Would it suffice to be able to define specific commands for the server to run on players when they win/lose?

**Comment by ghost** [comment]
Yes

**Comment by caseif** [comment]
Closed via 720207ab58b3387ca09262ac585befbaead9dd47.
