### ISSUE TITLE
serious doubts

### ISSUE THREAD

**Issue by MCG-server** [caseif/TTT#56]
I have read the issues " traitor tester " But I did not understand what should I do to create a tester ... I have to download another plugin ?? what is this metadata ?? I opened a file in the folder where there were TTT worlds and saw it was written metadata ( I have to put something in the braces after metadata ??) , please help me .

**Comment by caseif** [comment]
As I said in the previous issue, they are planned for 0.12 and thus not implemented yet. It's not possible to create them currently.
