### ISSUE TITLE
Right-clicking blocks in arena wizard registers twice

### ISSUE THREAD

**Issue by Shane1199** [caseif/TTT#64]
## TTT Version
0.11.1

## Steel Version
1.3.4

## Full output of `/version` command
CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT) _190 versions behind_

## Description of issue
When I right-click on a block when trying to define a new arena's border, it doubles the selection. It could be my mouse, but I tried it with the trackpad and had the same result. Tried on multiple blocks and locations within the same world, which does not have any other arenas. I do believe it has a WorldGuard selection, but I am OP and everything should be allowed as I have perms to everything. The server has plenty of unused memory and spare memory inside the allocated memory, so it's not an issue there. **NOTE:** It does work fine if you left-click, but the message just says to "click".

## Steps to replicate issue
1. /ttt createarena
2. (any singular word)
3. right-click (on any block)
(and then I type "cancel" to undo it all)

## Does the issue occur consistently?
Yes

## Console Errors?
None

**Comment by caseif** [comment]
Hm... to my knowledge Minecraft actually sends two packets for right-click events - it could be an issue stemming from that detail. I'll look further into it.

**Comment by Shane1199** [comment]
Alright thanks, sorry I forgot to add in the title. 😝  You could (as a temp solution) tell the player to left-click rather than to "click".

**Comment by caseif** [comment]
No worries. Most likely I'll just put out a hotfix as soon as I get the chance, probably at some point this week or so.
