### ISSUE TITLE
Test Code? /ttt xyzzy

### ISSUE THREAD

**Issue by Shane1199** [caseif/TTT#65]
## TTT Version
0.11.1

## Steel Version
Enter Steel version here.

## Full output of `/version` command
1.3.4

## Description of issue
This appears to be test code. I found it on the last and at the end of /ttt help. Typing /ttt xyzzy sends a message "Nothing happens.".

## Steps to replicate issue
Type /ttt xyzzy

## Does the issue occur consistently?
Yes

## Console Errors?
None

**Comment by caseif** [comment]
[Shhh.](https://en.wikipedia.org/wiki/Xyzzy_(computing)) ;)
