### ISSUE TITLE
Arena loading not working

### ISSUE THREAD

**Issue by royalnice** [caseif/TTT#69]
If im starting the server it says this: "[21:32:49 WARN]: [Steel] Arena store does not exist or contains malformed data. Not reading."
And if im loocking into the arenas.json its empty.
What do i have to do to fix that issue?

**Comment by caseif** [comment]
Sorry for the extremely late response on this. If it's still something you're interested in fixing, you would need to create an arena via the wizard (which works a bit like defining a region in WorldEdit). You can run `/ttt createarena` to initiate it (also see the [command documentation](https://github.com/caseif/TTT/wiki/Commands#arena-related)).
