### ISSUE TITLE
Can't use the TTT plugin in 1.12.2

### ISSUE THREAD

**Issue by Tape1001** [caseif/TTT#70]
## TTT Version
Any Version

## Steel Version
... idk what it is.

## Full output of `/version` command
Mohist version 1.12.2-274 (MC:1.12.2)

## Description of issue
I can't play with any Version of the TTT plugin. I just get an error messenge in the Server log

## Steps to replicate issue
Go to ploudos;com, set up a server, install Mohist 1.12.2. go to plugins and install any version of the TTT plugin

## Does the issue occur consistently?

yes

## Console Errors?
nope

**Comment by caseif** [comment]
Can you verify that [Steel](https://github.com/caseif/Steel/releases) is installed on the server? Otherwise, please provide the console error that you're running into.

**Comment by Tape1001** [comment]
Steel is on the server but it is still not working. (steel version 1.3.7) and here are the console errors:

![ploudos not working-1](https://user-images.githubusercontent.com/100618104/156252341-fab4251d-eca4-4f84-88e6-ac4d07820f46.png)
![ploudos not working-2](https://user-images.githubusercontent.com/100618104/156252368-0b3ed8ae-847f-487f-bbfb-04a5dbb4dd1a.PNG)
![ploudos not working-3](https://user-images.githubusercontent.com/100618104/156252376-25b0ddad-f07a-4934-95d3-23b3fa46d984.png)
![plodusod not workin-4](https://user-images.githubusercontent.com/100618104/156252389-b3877582-2037-4bb6-8fe0-985852fb9966.png)
![ploudos not workin-5](https://user-images.githubusercontent.com/100618104/156252403-52d650c2-0b33-4433-81a0-192425c8edc9.png)

**Comment by caseif** [comment]
This appears to be a compatibility issue with Mohist, as it does not seem to be setting metadata on its JAR in a Bukkit-compatible way. TTT uses this metadata to determine the current server software version.

I think this check was changed in a more recent version, so you can try updating to the latest release (0.11.4) to see if it resolves your issue.

**Comment by Tape1001** [comment]
I did it and the Log says that I'm clear,... but when I look into the log everything is still red and orange like in the pics before...

**Comment by caseif** [comment]
A lot of those errors are related to the update and telemetry services. The telemetry backend server is no longer functional (and I should probably get around to removing it from the plugin anyhow), so those errors are normal. I'm not sure what's going on with the updater, but it's not an issue for the functioning of the plugin.

In any event, you can suppress these components with the `enable-auto-update` and `enable-telemetry` config keys in the plugin's `config.yml` file.

**Comment by Tape1001** [comment]
ok. Then is everything doen and working, Thank you.
